title: U.S. Committee on the <br>Marine Transportation System
email: info@cmts.gov
description: >- # this means to ignore newlines
   The CMTS serves as a Federal interagency coordinating committee for the purpose of assessing the adequacy of the marine transportation system, promoting the integration of the marine transportation system with other modes of transportation and other uses of the marine environment, and coordinating, improving the coordination of, and making recommendations with regard to Federal policies that impact the marine transportation system.

baseurl: 

# Twitter handle. Only the handle, not the URL.
twitter: uscmts

#################################################################
#
# Digital Analytics Program (DAP) configuration
# DOD     - Department of Defense
# DOT     - Department of Transportation
#################################################################
dap:
   agency: DOD

  # Optional
   subagency: DOT

# Configuration for Google Analytics
ga:
  # ua: your-ua

# Site Navigation
primary_navigation:
  - name: Home
    url: /
  - name: "Why the MTS Matters"
    children:
      - name: "Why the MTS Matters"
        url: "/mts-why-mts-matters/"
      - name: "National Strategy for the MTS"
        url: "/mts-national-strategy/"
      - name: "MTS Priorities and CMTS Recommendations"
        url: "/mts-priorities/"
  - name: "About CMTS"
    children:
      - name: "What We Do"
        url: "/cmts-why-cmts-matters/"
      - name: "Organizational Structure"
        url: "/cmts-organizational-structure/"
      - name: "Messages From Leadership"
        url: "/cmts-leadership-messages/"
      - name: "Background - Why the MTS Matters"
        url: "/mts-why-mts-matters/"
      - name: "Background - History"
        url: "/cmts-history/"
      - name: "Background - Directives"
        url: "/cmts-directives/"    
      - name: "Meet our Team"
        url: "/cmts-team/"    
  - name: "Topics/Projects"
    children:
      - name: "Artic Transportation"
        url: "/topic-arctic/"
      - name: "COVID"
        url: "/topic-covid/"
      - name: "Future of Navigation"
        url: "/topic-future/"
      - name: "Maritime Innovative Science and Technology"
        url: "/topic-innovative-science/"
      - name: "Mariner and Workforce"
        url: "/topic-mariner-and-workforce/"
      - name: "Maritime Data"
        url: "/topic-maritime/"        
      - name: "Military to Mariner"
        url: "/topic-military/"
      - name: "Ocean Policy"
        url: "/topic-ocean-policy/"
      - name: "Offshore Energy"
        url: "/topic-offshore-energy/"
      - name: "Resilience"
        url: "/topic-resilience/"
      - name: "Supply Chain and Infrastructure"
        url: "/topic-supply/"    
  - name: "Resources"
    children:
      - name: "Compendium"
        url: "/resources-compendium/"
      - name: "Downloads"
        url: "/resources-downloads/"

# Search.gov configuration
#
# 1. Create an account with Search.gov https://search.usa.gov/signup
# 2. Add a new site.
# 3. Add your site/affiliate name here.
searchgov:

  # Only change this if you're using a CNAME. Learn more here: https://search.gov/manual/cname.html
  endpoint: https://search.usa.gov

  # Replace this with your search.gov account.
  affiliate: cmts

  # Replace this with your access key.
  access_key: V5W7zi9WBVxI9ee--1X1L90deBsHCC94s1VmIjqWWvw=

  # This renders the results within the page instead of sending to user to search.gov.
  inline: false

  # This allows Search.gov to present relevant type-ahead search suggestions in your website's search box.
  # If you do not want to present search suggestions, set this value to false.
  suggestions: true

##########################################################################################
# The values below here are more advanced and should only be
# changed if you know what they do
##########################################################################################
